"use client";

import { StyledProvider } from "@/providers/StyledProviders";
import "./globals.css";
import { Inter } from "next/font/google";
import { PianoContextProvider } from "./context/pianoContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("Elegancko");
  return (
    <html lang="en">
      <PianoContextProvider>
        <StyledProvider>
          <body className={inter.className}>{children}</body>
        </StyledProvider>
      </PianoContextProvider>
    </html>
  );
}
